module.exports = {
  reactStrictMode: true,
  env: {
    FIREBASE_CONFIG_APIKEY: process.env.FIREBASE_CONFIG_APIKEY,
    FIREBASE_CONFIG_AUTHDOMAIN: process.env.FIREBASE_CONFIG_AUTHDOMAIN,
    FIREBASE_CONFIG_PROJECTID: process.env.FIREBASE_CONFIG_PROJECTID,
    FIREBASE_CONFIG_STORAGEBUCKET: process.env.FIREBASE_CONFIG_STORAGEBUCKET,
    FIREBASE_CONFIG_MESSAGINGSENDERID: process.env.FIREBASE_CONFIG_MESSAGINGSENDERID,
    FIREBASE_CONFIG_APPID: process.env.FIREBASE_CONFIG_APPID,
    FIREBASE_CONFIG_MEASUREMENTID: process.env.FIREBASE_CONFIG_MEASUREMENTID
  }

}
